#!/usr/bin/env python
'''
Created on 04-Nov-2017

@author: karthikeyan
'''
import sys
sys.path.append('src/main/python')
from multiprocessing import Process
from com.jeavio.collector.metrics_collector import MetricsCollector
from com.jeavio.dbutil.DBUtil import DBUtil
from com.jeavio.controller import reports_controller
from com.jeavio.entities import report_data
# import all other scripts as well

def start_metric_collector(*args):
    collector = MetricsCollector()
    collector.do_collect_metrics()
    
   
def start_flask(*args):
    reports_controller.start_flask()

if __name__ == '__main__':
    dbutil = DBUtil()
    report_data.Base.metadata.create_all(dbutil.create_engine())
    p = Process(target=start_metric_collector, args=("Either so", ))
    p1 = Process(target=start_flask, args=("or so", ))
    p.start()
    p1.start()
